quarkus.application.name=quarkus-kafka-service
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.hibernate-orm.database.generation=update
dev.quarkus.h2.console.enabled=true
dev.quarkus.h2.console.path=/h2-console
app.output.mode=${APP_OUTPUT_MODE:kafka}
mp.messaging.incoming.input.connector=smallrye-kafka
mp.messaging.incoming.input.topic=${KAFKA_INPUT_TOPIC:input-topic}
mp.messaging.incoming.input.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.input.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
mp.messaging.outgoing.processed.connector=smallrye-kafka
mp.messaging.outgoing.processed.topic=${KAFKA_OUTPUT_TOPIC:processed-topic}
mp.messaging.outgoing.processed.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.processed.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
